package com.users.dao.po;

import java.io.Serializable;
import java.util.Date;

public class PageElement implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_id
     *
     * @mbg.generated
     */
    private Integer pageElementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.page_element_code
     *
     * @mbg.generated
     */
    private String pageElementCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.is_disable
     *
     * @mbg.generated
     */
    private Integer isDisable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.create_datetime
     *
     * @mbg.generated
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_element.update_datetime
     *
     * @mbg.generated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_element
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_id
     *
     * @return the value of page_element.page_element_id
     *
     * @mbg.generated
     */
    public Integer getPageElementId() {
        return pageElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_id
     *
     * @param pageElementId the value for page_element.page_element_id
     *
     * @mbg.generated
     */
    public void setPageElementId(Integer pageElementId) {
        this.pageElementId = pageElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.page_element_code
     *
     * @return the value of page_element.page_element_code
     *
     * @mbg.generated
     */
    public String getPageElementCode() {
        return pageElementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.page_element_code
     *
     * @param pageElementCode the value for page_element.page_element_code
     *
     * @mbg.generated
     */
    public void setPageElementCode(String pageElementCode) {
        this.pageElementCode = pageElementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.is_disable
     *
     * @return the value of page_element.is_disable
     *
     * @mbg.generated
     */
    public Integer getIsDisable() {
        return isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.is_disable
     *
     * @param isDisable the value for page_element.is_disable
     *
     * @mbg.generated
     */
    public void setIsDisable(Integer isDisable) {
        this.isDisable = isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.create_datetime
     *
     * @return the value of page_element.create_datetime
     *
     * @mbg.generated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.create_datetime
     *
     * @param createDatetime the value for page_element.create_datetime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_element.update_datetime
     *
     * @return the value of page_element.update_datetime
     *
     * @mbg.generated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_element.update_datetime
     *
     * @param updateDatetime the value for page_element.update_datetime
     *
     * @mbg.generated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}