package com.users.dao.mapper;

import com.users.dao.po.File;
import com.users.dao.po.FileExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @SelectProvider(type=FileSqlProvider.class, method="countByExample")
    long countByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @DeleteProvider(type=FileSqlProvider.class, method="deleteByExample")
    int deleteByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Delete({
        "delete from file",
        "where file_id = #{fileId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Insert({
        "insert into file (file_id, file_path, ",
        "is_disable, create_datetime, ",
        "update_datetime)",
        "values (#{fileId,jdbcType=INTEGER}, #{filePath,jdbcType=VARCHAR}, ",
        "#{isDisable,jdbcType=INTEGER}, #{createDatetime,jdbcType=TIMESTAMP}, ",
        "#{updateDatetime,jdbcType=TIMESTAMP})"
    })
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @InsertProvider(type=FileSqlProvider.class, method="insertSelective")
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @SelectProvider(type=FileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="file_id", property="fileId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="file_path", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_disable", property="isDisable", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_datetime", property="updateDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<File> selectByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "file_id, file_path, is_disable, create_datetime, update_datetime",
        "from file",
        "where file_id = #{fileId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="file_id", property="fileId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="file_path", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_disable", property="isDisable", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_datetime", property="updateDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    File selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @UpdateProvider(type=FileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated
     */
    @Update({
        "update file",
        "set file_path = #{filePath,jdbcType=VARCHAR},",
          "is_disable = #{isDisable,jdbcType=INTEGER},",
          "create_datetime = #{createDatetime,jdbcType=TIMESTAMP},",
          "update_datetime = #{updateDatetime,jdbcType=TIMESTAMP}",
        "where file_id = #{fileId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(File record);
}