package com.users.dao.mapper;

import com.users.dao.po.Oper;
import com.users.dao.po.OperExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @SelectProvider(type=OperSqlProvider.class, method="countByExample")
    long countByExample(OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @DeleteProvider(type=OperSqlProvider.class, method="deleteByExample")
    int deleteByExample(OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @Delete({
        "delete from oper",
        "where oper_id = #{operId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @Insert({
        "insert into oper (oper_id, oper_name, ",
        "oper_code, oper_url, ",
        "parent_oper_id, is_disable, ",
        "create_datetime, update_datetime)",
        "values (#{operId,jdbcType=INTEGER}, #{operName,jdbcType=VARCHAR}, ",
        "#{operCode,jdbcType=VARCHAR}, #{operUrl,jdbcType=VARCHAR}, ",
        "#{parentOperId,jdbcType=INTEGER}, #{isDisable,jdbcType=INTEGER}, ",
        "#{createDatetime,jdbcType=TIMESTAMP}, #{updateDatetime,jdbcType=TIMESTAMP})"
    })
    int insert(Oper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @InsertProvider(type=OperSqlProvider.class, method="insertSelective")
    int insertSelective(Oper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @SelectProvider(type=OperSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="oper_id", property="operId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="oper_name", property="operName", jdbcType=JdbcType.VARCHAR),
        @Result(column="oper_code", property="operCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="oper_url", property="operUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_oper_id", property="parentOperId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_disable", property="isDisable", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_datetime", property="updateDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Oper> selectByExample(OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "oper_id, oper_name, oper_code, oper_url, parent_oper_id, is_disable, create_datetime, ",
        "update_datetime",
        "from oper",
        "where oper_id = #{operId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="oper_id", property="operId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="oper_name", property="operName", jdbcType=JdbcType.VARCHAR),
        @Result(column="oper_code", property="operCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="oper_url", property="operUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_oper_id", property="parentOperId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_disable", property="isDisable", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_datetime", property="updateDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    Oper selectByPrimaryKey(Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OperSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Oper record, @Param("example") OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OperSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Oper record, @Param("example") OperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OperSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Oper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    @Update({
        "update oper",
        "set oper_name = #{operName,jdbcType=VARCHAR},",
          "oper_code = #{operCode,jdbcType=VARCHAR},",
          "oper_url = #{operUrl,jdbcType=VARCHAR},",
          "parent_oper_id = #{parentOperId,jdbcType=INTEGER},",
          "is_disable = #{isDisable,jdbcType=INTEGER},",
          "create_datetime = #{createDatetime,jdbcType=TIMESTAMP},",
          "update_datetime = #{updateDatetime,jdbcType=TIMESTAMP}",
        "where oper_id = #{operId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Oper record);
}