package com.users.dao.mapper;

import com.users.dao.po.Oper;
import com.users.dao.po.OperExample.Criteria;
import com.users.dao.po.OperExample.Criterion;
import com.users.dao.po.OperExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OperSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String countByExample(OperExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("oper");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String deleteByExample(OperExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("oper");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String insertSelective(Oper record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("oper");
        
        if (record.getOperId() != null) {
            sql.VALUES("oper_id", "#{operId,jdbcType=INTEGER}");
        }
        
        if (record.getOperName() != null) {
            sql.VALUES("oper_name", "#{operName,jdbcType=VARCHAR}");
        }
        
        if (record.getOperCode() != null) {
            sql.VALUES("oper_code", "#{operCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOperUrl() != null) {
            sql.VALUES("oper_url", "#{operUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getParentOperId() != null) {
            sql.VALUES("parent_oper_id", "#{parentOperId,jdbcType=INTEGER}");
        }
        
        if (record.getIsDisable() != null) {
            sql.VALUES("is_disable", "#{isDisable,jdbcType=INTEGER}");
        }
        
        if (record.getCreateDatetime() != null) {
            sql.VALUES("create_datetime", "#{createDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateDatetime() != null) {
            sql.VALUES("update_datetime", "#{updateDatetime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String selectByExample(OperExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("oper_id");
        } else {
            sql.SELECT("oper_id");
        }
        sql.SELECT("oper_name");
        sql.SELECT("oper_code");
        sql.SELECT("oper_url");
        sql.SELECT("parent_oper_id");
        sql.SELECT("is_disable");
        sql.SELECT("create_datetime");
        sql.SELECT("update_datetime");
        sql.FROM("oper");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Oper record = (Oper) parameter.get("record");
        OperExample example = (OperExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("oper");
        
        if (record.getOperId() != null) {
            sql.SET("oper_id = #{record.operId,jdbcType=INTEGER}");
        }
        
        if (record.getOperName() != null) {
            sql.SET("oper_name = #{record.operName,jdbcType=VARCHAR}");
        }
        
        if (record.getOperCode() != null) {
            sql.SET("oper_code = #{record.operCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOperUrl() != null) {
            sql.SET("oper_url = #{record.operUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getParentOperId() != null) {
            sql.SET("parent_oper_id = #{record.parentOperId,jdbcType=INTEGER}");
        }
        
        if (record.getIsDisable() != null) {
            sql.SET("is_disable = #{record.isDisable,jdbcType=INTEGER}");
        }
        
        if (record.getCreateDatetime() != null) {
            sql.SET("create_datetime = #{record.createDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateDatetime() != null) {
            sql.SET("update_datetime = #{record.updateDatetime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("oper");
        
        sql.SET("oper_id = #{record.operId,jdbcType=INTEGER}");
        sql.SET("oper_name = #{record.operName,jdbcType=VARCHAR}");
        sql.SET("oper_code = #{record.operCode,jdbcType=VARCHAR}");
        sql.SET("oper_url = #{record.operUrl,jdbcType=VARCHAR}");
        sql.SET("parent_oper_id = #{record.parentOperId,jdbcType=INTEGER}");
        sql.SET("is_disable = #{record.isDisable,jdbcType=INTEGER}");
        sql.SET("create_datetime = #{record.createDatetime,jdbcType=TIMESTAMP}");
        sql.SET("update_datetime = #{record.updateDatetime,jdbcType=TIMESTAMP}");
        
        OperExample example = (OperExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Oper record) {
        SQL sql = new SQL();
        sql.UPDATE("oper");
        
        if (record.getOperName() != null) {
            sql.SET("oper_name = #{operName,jdbcType=VARCHAR}");
        }
        
        if (record.getOperCode() != null) {
            sql.SET("oper_code = #{operCode,jdbcType=VARCHAR}");
        }
        
        if (record.getOperUrl() != null) {
            sql.SET("oper_url = #{operUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getParentOperId() != null) {
            sql.SET("parent_oper_id = #{parentOperId,jdbcType=INTEGER}");
        }
        
        if (record.getIsDisable() != null) {
            sql.SET("is_disable = #{isDisable,jdbcType=INTEGER}");
        }
        
        if (record.getCreateDatetime() != null) {
            sql.SET("create_datetime = #{createDatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateDatetime() != null) {
            sql.SET("update_datetime = #{updateDatetime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("oper_id = #{operId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, OperExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}