package com.users.dao.mapper;

import com.users.dao.po.PageElement;
import com.users.dao.po.PageElementExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PageElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @SelectProvider(type=PageElementSqlProvider.class, method="countByExample")
    long countByExample(PageElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PageElementSqlProvider.class, method="deleteByExample")
    int deleteByExample(PageElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @Delete({
        "delete from page_element",
        "where page_element_id = #{pageElementId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pageElementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @Insert({
        "insert into page_element (page_element_id, page_element_code, ",
        "is_disable, create_datetime, ",
        "update_datetime)",
        "values (#{pageElementId,jdbcType=INTEGER}, #{pageElementCode,jdbcType=VARCHAR}, ",
        "#{isDisable,jdbcType=INTEGER}, #{createDatetime,jdbcType=TIMESTAMP}, ",
        "#{updateDatetime,jdbcType=TIMESTAMP})"
    })
    int insert(PageElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @InsertProvider(type=PageElementSqlProvider.class, method="insertSelective")
    int insertSelective(PageElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @SelectProvider(type=PageElementSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="page_element_id", property="pageElementId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="page_element_code", property="pageElementCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_disable", property="isDisable", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_datetime", property="updateDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PageElement> selectByExample(PageElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "page_element_id, page_element_code, is_disable, create_datetime, update_datetime",
        "from page_element",
        "where page_element_id = #{pageElementId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="page_element_id", property="pageElementId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="page_element_code", property="pageElementCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_disable", property="isDisable", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_datetime", property="updateDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    PageElement selectByPrimaryKey(Integer pageElementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PageElementSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PageElement record, @Param("example") PageElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PageElementSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PageElement record, @Param("example") PageElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PageElementSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PageElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbg.generated
     */
    @Update({
        "update page_element",
        "set page_element_code = #{pageElementCode,jdbcType=VARCHAR},",
          "is_disable = #{isDisable,jdbcType=INTEGER},",
          "create_datetime = #{createDatetime,jdbcType=TIMESTAMP},",
          "update_datetime = #{updateDatetime,jdbcType=TIMESTAMP}",
        "where page_element_id = #{pageElementId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PageElement record);
}