package com.users.dao.mapper;

import com.users.dao.po.PermissionElement;
import com.users.dao.po.PermissionElementExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PermissionElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @SelectProvider(type=PermissionElementSqlProvider.class, method="countByExample")
    long countByExample(PermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PermissionElementSqlProvider.class, method="deleteByExample")
    int deleteByExample(PermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @Delete({
        "delete from permission_element",
        "where permission_element_id = #{permissionElementId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer permissionElementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @Insert({
        "insert into permission_element (permission_element_id, permission_id, ",
        "element_id, element_type, ",
        "create_datetime)",
        "values (#{permissionElementId,jdbcType=INTEGER}, #{permissionId,jdbcType=INTEGER}, ",
        "#{elementId,jdbcType=INTEGER}, #{elementType,jdbcType=INTEGER}, ",
        "#{createDatetime,jdbcType=TIMESTAMP})"
    })
    int insert(PermissionElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @InsertProvider(type=PermissionElementSqlProvider.class, method="insertSelective")
    int insertSelective(PermissionElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @SelectProvider(type=PermissionElementSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="permission_element_id", property="permissionElementId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.INTEGER),
        @Result(column="element_id", property="elementId", jdbcType=JdbcType.INTEGER),
        @Result(column="element_type", property="elementType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PermissionElement> selectByExample(PermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "permission_element_id, permission_id, element_id, element_type, create_datetime",
        "from permission_element",
        "where permission_element_id = #{permissionElementId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="permission_element_id", property="permissionElementId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.INTEGER),
        @Result(column="element_id", property="elementId", jdbcType=JdbcType.INTEGER),
        @Result(column="element_type", property="elementType", jdbcType=JdbcType.INTEGER),
        @Result(column="create_datetime", property="createDatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    PermissionElement selectByPrimaryKey(Integer permissionElementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PermissionElementSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PermissionElement record, @Param("example") PermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PermissionElementSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PermissionElement record, @Param("example") PermissionElementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PermissionElementSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PermissionElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_element
     *
     * @mbg.generated
     */
    @Update({
        "update permission_element",
        "set permission_id = #{permissionId,jdbcType=INTEGER},",
          "element_id = #{elementId,jdbcType=INTEGER},",
          "element_type = #{elementType,jdbcType=INTEGER},",
          "create_datetime = #{createDatetime,jdbcType=TIMESTAMP}",
        "where permission_element_id = #{permissionElementId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PermissionElement record);
}